### ISSUE TITLE
[3.0.0005] Error Message is thrown when user try to take backup for signing keys when signing is not done

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#684]
Environment: Win 7 64bit and Win 8.1

Preq: Unr-register Signing keys

Steps to Reproduce:
1. Goto Blackberry->Options
2. Goto Blackberry->signing
3. Observe that Signing is not done

![reg](https://cloud.githubusercontent.com/assets/5992422/6079935/b47ecaaa-ae31-11e4-9929-9d0c00e87f2f.png)
1. Goto Blackberry->Backup
2. Observe that "Backup..." button is enabled.
3. Press "Backup..." button
4. Save the backup file.

Actual Result on Win 7 64bit:

Error message is thrown as follows:

![export failed](https://cloud.githubusercontent.com/assets/5992422/6079951/f33c2558-ae31-11e4-8711-b59bc3910366.PNG)

Actual Result on Win 8.1 64bit:

Successful message is thrown as follows:

![success](https://cloud.githubusercontent.com/assets/5992422/6079960/0e8037c8-ae32-11e4-8e61-f4fb6140af3f.PNG)

On both Win 7 64bit and Win 8.1, when the .zip file is opened, it is shown as empty.

![empty](https://cloud.githubusercontent.com/assets/5992422/6079965/1f06aa6e-ae32-11e4-9da5-2e981f5ef031.png)

**Comment by phofman** [comment]
HINT: all errors displayed on UI are mostly caused by internal exception. Exceptions are in 99% of cases printed on BlackBerry-specific output window. Could you please also attach those logs next time? The same is about communication with all Java tools, in case you have other issues/misbehaviors (like about the removal of debug-token).

BTW. There is a magic 'Import' button on your screenshot. It is supposed to let you use a different developer certificate (default is: author.p12, but you can always name it differently and import here).

![blackberry-output](https://cloud.githubusercontent.com/assets/475630/6116687/090aa7e0-b0af-11e4-909b-8d5086e02a78.png)

**Comment by pvallabhaneni** [comment]
Verified in 3.0.0015 plugin and found that the issue is sill reproducing.

**Comment by phofman** [comment]
So where are the logs I kindly asked?? ;)

**Comment by dbrgss** [comment]
08:55:12.011: BlackBerry plugin started
08:55:12.016:  \* registered services
08:55:12.016:  \* loaded NDK descriptions
08:55:12.029:  \* registered editors
08:55:12.299:  \* registered build-platforms manager
08:55:12.301:  \* initialized menus
08:55:12.301: -------------------- DONE (3.0.0)
08:55:12.718: Changed active NDK to: "BlackBerry 10 Native SDK 10.3.1 (10.3.1.995)"
08:55:12.784: Loaded list of Target Devices
08:55:12.784: Found active Target Devices:
08:55:12.784:  \* device - none
08:55:12.784:  \* simulator - none
08:56:27.011: Unable to export profile to file: "C:\Users\dburgess\Documents\Visual Studio 2013\Projects\Client Application20\profile_backup_2015-02-13.zip"

### (ArgumentNullException) Value cannot be null.

Parameter name: path2
   at System.IO.Path.Combine(String path1, String path2)
   at BlackBerry.NativeCore.Model.DeveloperDefinition.BackupProfile(String outputFile)

**Comment by phofman** [comment]
Fixed the exception and the way 'Register' and 'Unregister' buttons are enabled.
It's available as part of #694 pull-request.
